### ISSUE TITLE
Sactter function:  error: no matching function for call to ‘collect_arguments(pybind11::tuple&)’

### ISSUE THREAD

**Issue by DeepakVellampalli** [AndyYuan96/PointCloudDynamicVoxel#1]
While trying to build scatter using python setup.py install i got erroe below. Kindly help

/home/user/anaconda3/envs/mvf/lib/python3.6/site-packages/torch/include/pybind11/cast.h:2108:44: error: no matching function for call to ‘collect_arguments(pybind11::object)’
     return detail::collect_arguments<policy>(std::forward<Args>(args)...).call(derived().ptr());

**Comment by AndyYuan96** [comment]
Sorry, I haven't encountered the problem in the past, it looks like the problem is related to pybind11, pybind11 is integrated in pytorch, so it's related to pytorch. Maybe you should change the pytorch version, I only test on pytorch1.1 and pytorch1.4.
